version: '3.9'
networks:
  ztp:
    driver: bridge

services:
  go-service:
    build:
      context: './'
      dockerfile: 'Dockerfile'
    image: 'corey888773/ztp-api:latest'
    ports:
      - '8000:8000'
    hostname: 'ztp-api'
    environment:
      - MONGO_URI=mongodb://ztp-mongo:27017
    depends_on:
      - mongo-db
    networks:
      - ztp

  mongo-db:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    networks:
      - ztp
    hostname: 'ztp-mongo'
    volumes:
      - ./mongodb:/var/lib/mongodb/data

